---
- name: Find Teams InstallLocation
  ansible.windows.win_shell: |
    Get-AppXPackage -AllUsers -Name "*msteams*" | Select-Object -ExpandProperty InstallLocation | ConvertTo-Json
  register: result_teams_install_location
  tags: "find-meeting-addin"

- name: Debug result_teams_install_location
  ansible.builtin.debug:
    var: result_teams_install_location
  tags: "find-meeting-addin"

- name: Set fact teams_install_locations
  ansible.builtin.set_fact:
    teams_install_locations: "{{ result_teams_install_location.stdout_lines }}"
  tags: "find-meeting-addin"

- name: Debug result_teams_install_locations length
  ansible.builtin.debug:
    msg: '{{ teams_install_locations | length }}'
  tags: "find-meeting-addin"

- name: Set fact teams_install_location
  ansible.builtin.set_fact:
    teams_install_location: "{{ teams_install_locations | last | from_json }}"
  tags: "find-meeting-addin"

- name: Debug result_teams_install_location
  ansible.builtin.debug:
    msg: '{{ teams_install_location }}\MicrosoftTeamsMeetingAddinInstaller.msi'
  tags: "find-meeting-addin"

# - name: Install MeetingAddin - find dir
#   ansible.windows.win_find:
#     paths:
#       - '{{ ansible_env["ProgramFiles"] }}\WindowsApps'
#     file_type: directory
#     patterns: MSTeams_*
#   register: results_find_teams_dir

# - name: Debug results_find_teams_dir
#   ansible.builtin.debug:
#     var: results_find_teams_dir

# - name: Msg results_find_teams_dir
#   ansible.builtin.debug:
#     msg: '{{ results_find_teams_dir.files | map(attribute="path") | last }}'


# - name: Set fact meetingaddin msi file
#   ansible.builtin.set_fact:
#     teams_meeting_addin_msi_file_path: '{{ results_find_teams_dir.files | map(attribute="path") | last }}\MicrosoftTeamsMeetingAddinInstaller.msi'

- name: Install Teams Meeting Addin
  block:
    - name: Set fact meetingaddin msi file
      ansible.builtin.set_fact:
        teams_meeting_addin_msi_file_path: '{{ teams_install_location }}\MicrosoftTeamsMeetingAddinInstaller.msi'

    - name: Get teams_meeting_addin_msi binary version
      ansible.windows.win_shell: |
        Get-AppLockerFileInformation -Path "{{ teams_meeting_addin_msi_file_path }}" | Select -ExpandProperty Publisher | select BinaryVersion | ConvertTo-Json
      register: exe_file_version

    # - debug:
    #     msg: "{{ exe_file_version.stdout }}"

    - name: Set fact teams_meeting_addin_msi_binary_version
      ansible.builtin.set_fact:
        teams_meeting_addin_msi_binary_version: "{{ exe_file_version.stdout | from_json }}"

    # - debug:
    #     msg: "{{ teams_meeting_addin_msi_binary_version.BinaryVersion }}"

    # - debug:
    #     msg: "{{ teams_meeting_addin_msi_binary_version.BinaryVersion.MajorPartNumber }}.{{ teams_meeting_addin_msi_binary_version.BinaryVersion.MinorPartNumber }}.{{ teams_meeting_addin_msi_binary_version.BinaryVersion.BuildPartNumber }}.{{ teams_meeting_addin_msi_binary_version.BinaryVersion.PrivatePartNumber }}"

    - name: Set fact teams_meeting_addin_msi_binary_version_string
      ansible.builtin.set_fact:
        teams_meeting_addin_msi_binary_version_string: "{{ teams_meeting_addin_msi_binary_version.BinaryVersion.MajorPartNumber }}.{{ teams_meeting_addin_msi_binary_version.BinaryVersion.MinorPartNumber }}.{{ teams_meeting_addin_msi_binary_version.BinaryVersion.BuildPartNumber }}.{{ teams_meeting_addin_msi_binary_version.BinaryVersion.PrivatePartNumber }}"

    - name: Set fact teams_addin dirs and files
      ansible.builtin.set_fact:
        teams_addin_target_dir: '{{ ansible_env["ProgramFiles(x86)"] }}\Microsoft\TeamsMeetingAddin\{{ teams_meeting_addin_msi_binary_version_string }}\'
        teams_addin_loader_dll_x64: '{{ ansible_env["ProgramFiles(x86)"] }}\Microsoft\TeamsMeetingAddin\{{ teams_meeting_addin_msi_binary_version_string }}\x64\Microsoft.Teams.AddinLoader.dll'
        teams_addin_loader_dll_x86: '{{ ansible_env["ProgramFiles(x86)"] }}\Microsoft\TeamsMeetingAddin\{{ teams_meeting_addin_msi_binary_version_string }}\x86\Microsoft.Teams.AddinLoader.dll'

    - name: Debug teams_meeting_addin_msi_binary_version_string
      ansible.builtin.debug:
        msg: "{{ teams_meeting_addin_msi_binary_version_string }}"

    - name: Debug teams_addin_target_dir
      ansible.builtin.debug:
        msg: "{{ teams_addin_target_dir }}"

    - name: Uninstall Teams Meeting Addin
      ansible.windows.win_package:
        path: '{{ teams_meeting_addin_msi_file_path }}'
        state: absent
        arguments: 'ALLUSERS=1'
      register: result_teams_meeting_addin_uninstall

    - name: Debug result_teams_meeting_addin_uninstall
      ansible.builtin.debug:
        var: result_teams_meeting_addin_uninstall

    - name: Install Teams Meeting Addin
      ansible.windows.win_package:
        path: '{{ teams_meeting_addin_msi_file_path }}'
        state: present
        arguments: 'ALLUSERS=1 TARGETDIR="{{ teams_addin_target_dir }}"'
      register: result_teams_meeting_addin_install

    - name: Debug result_teams_meeting_addin_install
      ansible.builtin.debug:
        var: result_teams_meeting_addin_install
  when:
    - result_teams_install_location is defined
    - result_teams_install_location | length > 0


- name: Register Teams AddinLoader
  block:
    - name: Microsoft.Teams.AddinLoader - x64 dll register
      ansible.windows.win_shell: |
        regsvr32 /s "{{ teams_addin_loader_dll_x64 }}"
      args:
        executable: cmd
      register: result_x64_dll_register

    - name: Microsoft.Teams.AddinLoader - x64 dll result
      ansible.builtin.debug:
        var: result_x64_dll_register

    - name: Microsoft.Teams.AddinLoader - x86 dll register
      ansible.windows.win_shell: |
        regsvr32 /s "{{ teams_addin_loader_dll_x86 }}"
      args:
        executable: cmd
      register: result_x86_dll_register

    - name: Microsoft.Teams.AddinLoader - x86 dll result
      ansible.builtin.debug:
        var: result_x86_dll_register
  when:
    - teams_addin_loader_dll_x64 is defined
    - teams_addin_loader_dll_x64 | length > 0

...
